<a href="https://colab.research.google.com/github/DhushyanthRavichandran/AI/blob/main/ML/catboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
!pip install catboost
from catboost import CatBoostClassifier

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 2.3 MB/s eta 0:00:00


In [ ]:
test=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/amazon-employee-access-challenge/test.csv")
train=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/amazon-employee-access-challenge/train.csv")

In [ ]:
train

ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0           1     39353   85475         117961         118300         123472   
1           1     17183    1540         117961         118343         123125   
2           1     36724   14457         118219         118220         117884   
3           1     36135    5396         117961         118343         119993   
4           1     42680    5905         117929         117930         119569   
...       ...       ...     ...            ...            ...            ...   
32764       1     23497   16971         117961         118300         119993   
32765       1     25139  311198          91261         118026         122392   
32766       1     34924   28805         117961         118327         120299   
32767       1     80574   55643         118256         118257         117945   
32768       1     14354   59575         117916         118150         117920   

       ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0          117905            117906       290919     117908  
1          118536            118536       308574     118539  
2          117879            267952        19721     117880  
3          118321            240983       290919     118322  
4          119323            123932        19793     119325  
...           ...               ...          ...        ...  
32764      118321            240983       290919     118322  
32765      121143            173805       249618     121145  
32766      124922            152038       118612     124924  
32767      280788            280788       292795     119082  
32768      118568            122142        19721     118570  

[32769 rows x 10 columns]

In [ ]:
train['ROLE_ROLLUP_2'].unique()

array([118300, 118343, 118220, 117930, 117952, 117969, 118413, 118080,
       118041, 118463, 118026, 118052, 118446, 118587, 118091, 119070,
       119135, 118266, 118327, 118225, 117891, 118386, 117962, 118150,
       118580, 118257, 118178, 118603, 118270, 118107, 117976, 118574,
       118170, 117903, 117911, 121786, 117981, 118340, 120343, 119091,
       118316, 118888, 118115, 119256, 121013, 119597, 119302, 117984,
       118442, 118596, 118182, 117877, 118213, 117936, 119063, 118124,
       118011,  23779, 119921, 118085, 117917, 118991, 118164, 122974,
       118291, 118076, 118217, 119281, 118977, 117933, 117923, 126919,
       159716, 117927, 118753, 118024, 117979, 119692, 117960, 126102,
       124035, 117944, 119171, 130600, 119666, 118659, 120865, 118193,
       138799, 118102, 118007, 118583, 124335, 145248, 118096, 117954,
       118855, 117919, 126975, 117940, 120141, 118954, 118139, 118121,
       118551, 119403, 131854, 120216, 117894, 130685, 120862, 121006,
      

In [ ]:
train['ACTION'].unique()

array([1, 0])

In [ ]:
y=train['ACTION']
y

0        1
1        1
2        1
3        1
4        1
        ..
32764    1
32765    1
32766    1
32767    1
32768    1
Name: ACTION, Length: 32769, dtype: int64

In [ ]:
x=train.drop(columns=['ACTION'],axis=1).values
x

array([[ 39353,  85475, 117961, ..., 117906, 290919, 117908],
       [ 17183,   1540, 117961, ..., 118536, 308574, 118539],
       [ 36724,  14457, 118219, ..., 267952,  19721, 117880],
       ...,
       [ 34924,  28805, 117961, ..., 152038, 118612, 124924],
       [ 80574,  55643, 118256, ..., 280788, 292795, 119082],
       [ 14354,  59575, 117916, ..., 122142,  19721, 118570]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33)


In [ ]:
cat_features = [0, 1, 4, 5]
params = {
    'iterations': 500,

    'depth': 10,
    'loss_function': 'Logloss',
    'cat_features': cat_features
}

cb=CatBoostClassifier(learning_rate= 0.05)
cab=cb.fit(x_train,y_train,cat_features)

SyntaxError: ignored

In [ ]:
cb.score(x_train,y_train)

0.9808244135732179

In [ ]:
pred=cb.predict(x_test)
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pred)*100
acc

95.31163306824487