<a href="https://colab.research.google.com/github/DhushyanthRavichandran/AI/blob/main/DL/neuralnetwork_tf_mnist_img.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-7.9575479e-03,  3.4505501e-04,  2.8529710e-01, -5.9452718e-01,
         2.2593026e-01, -9.2253441e-01,  2.3069555e-01, -4.6737120e-01,
         6.1608098e-02,  3.8543928e-02]], dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.1042712 , 0.10514052, 0.13980517, 0.05799899, 0.13174695,
        0.04178002, 0.13237625, 0.06586331, 0.11178315, 0.10923446]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [ ]:
loss_fn(y_train[:1], predictions).numpy()


3.1753368

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2989 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1420 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1081 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0882 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0745 - accuracy: 0.9763


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0727 - accuracy: 0.9780 - 825ms/epoch - 3ms/step


[0.07265628129243851, 0.9779999852180481]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.59630417e-07, 2.98689851e-10, 6.10281631e-06, 1.14565555e-04,
        6.12255663e-11, 8.06779894e-07, 2.43270329e-13, 9.99876380e-01,
        5.01431941e-07, 1.46052764e-06],
       [1.38331577e-08, 2.92517507e-04, 9.99700308e-01, 6.90226125e-06,
        1.97359545e-15, 3.66936916e-08, 4.34229008e-09, 2.20235275e-14,
        2.37209449e-07, 6.63231626e-15],
       [4.20754873e-07, 9.99301076e-01, 5.65038135e-05, 2.96113581e-06,
        2.38913271e-04, 2.53092253e-06, 5.95395340e-06, 3.79683828e-04,
        1.09026660e-05, 1.12274302e-06],
       [9.99278724e-01, 2.39386377e-08, 1.34023387e-04, 2.93753897e-06,
        1.33310414e-06, 4.45125370e-05, 5.36033476e-04, 9.87215685e-07,
        1.22436632e-06, 2.05041076e-07],
       [1.39843166e-06, 4.98369623e-10, 5.35537874e-05, 3.17167235e-08,
        9.98997748e-01, 5.76241689e-07, 3.52525171e-06, 1.73840654e-05,
        3.72137401e-06, 9.22089559e-04]], dtype=float32)>